build:
	docker build -t dwmkerr/node:6-imagemagick ./node6/.
	docker build -t dwmkerr/node:8-imagemagick ./node8/.
	docker build -t dwmkerr/node:10-imagemagick ./node10/.
	docker build -t dwmkerr/node:12-imagemagick ./node12/.

push:
	docker push dwmkerr/node:6-imagemagick
	docker push dwmkerr/node:8-imagemagick
	docker push dwmkerr/node:10-imagemagick
	docker push dwmkerr/node:12-imagemagick
