build:
	docker build -t dwmkerr/node:10-imagemagick ./node10/.
	docker build -t dwmkerr/node:12-imagemagick ./node12/.
	docker build -t dwmkerr/node:14-imagemagick ./node14/.

push:
	docker push dwmkerr/node:10-imagemagick
	docker push dwmkerr/node:12-imagemagick
	docker push dwmkerr/node:14-imagemagick
